version: '3.5'
services:
  hilbertsen.com:
    image: markhilb/hilbertsen.com:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11000:80"

networks:
  default:
    name: hilbertsen_network
